### ISSUE TITLE
adidas.it

### ISSUE THREAD

**Issue by magboo** [kdcz/3s_atc#7]
can't log  in on adidas.it..ty

**Comment by kdcz** [comment]
Works fine for me, make sure you have PhantomJS.exe in your folder else the problem is related to your internet connection or adidas has blocked you?

**Comment by magboo** [comment]
i dont know what hapen working properly when the chromedriver is in the folder but now cant loggin and cant connect
![capture](https://cloud.githubusercontent.com/assets/25304953/23025857/8c0aebbe-f45f-11e6-8e8a-25b2abb929f6.JPG)

**Comment by magboo** [comment]
dont know what happen working properly when i tried before using chromedriver but now cant log in anymore
![capture](https://cloud.githubusercontent.com/assets/25304953/23025945/dc49d810-f45f-11e6-98f0-32541e29137a.JPG)

**Comment by magboo** [comment]
i can still access adidas.it on my browser

**Comment by kdcz** [comment]
Process should be : Connecting to login page, Logging in, Logged in
So if you are stuck more than 1 minute on "Connecting to login page", then PhantomJS can't access the adidas login page, make sure you have PhantomJS.exe in the application folder and make sure PhantomJS is allowed in your firewall

**Comment by kdcz** [comment]
Nevermind, my bad I forgot to put some DLL's to the root folder, sorry again it should work now!

**Comment by magboo** [comment]
the captcha browser load faster but the problem is the item doesnt add to cart even i continue to solve captcha.ty

**Comment by kdcz** [comment]
Pushed a new update, don't forget to update your sitekey.php with the new one and update your settings in the application!

**Comment by magboo** [comment]
run a test and getting no size  available

**Comment by kdcz** [comment]
For which product

**Comment by magboo** [comment]
BB4486 i tried many times but cant cart??

**Comment by magboo** [comment]
![capture](https://cloud.githubusercontent.com/assets/25304953/23102739/26ab3fc4-f6af-11e6-8c68-a30009deb263.JPG)

**Comment by kdcz** [comment]
Should be fixed now can you try again please ? Thanks

**Comment by magboo** [comment]
just tried but keep solving the captcha and doesnt cart..the bot work so fine before the update with chrome driver

**Comment by kdcz** [comment]
You need to update your sitekey.php

**Comment by magboo** [comment]
updated sitekey but still doesnt cart
![capture](https://cloud.githubusercontent.com/assets/25304953/23128614/d8dcbbb6-f77f-11e6-90cc-57dd4d50b96f.JPG)

**Comment by kdcz** [comment]
-Did you solved the captcha by making a right click and press "Solve captcha"?
-Did you press the submit button after solving the captcha

**Comment by magboo** [comment]
i solved the captcha 10 times but nothing happens
i also updated the path

**Comment by kdcz** [comment]
I cant really help you because I dont have this issue but I can see what I can do onavec teamviewer

**Comment by magboo** [comment]
finally working now ty very much
